CREATE DATABASE SACHINJOIN;
CREATE TABLE SACHIN(
AADHAR bigint,
FIRSTNAME varchar(255),
LASTNAME varchar(255),
CITY varchar(255)
);
INSERT INTO SACHIN VALUES(1,'SHARAD','PAWAR','BARAMATI');
INSERT INTO SACHIN VALUES(2,'AJIT','PAWAR','PUNE');
INSERT INTO SACHIN VALUES(3,'SANJAY','RAUT','MUMBAI');
SELECT*FROM SACHIN;

CREATE TABLE PAWAR(
ACCOUNTNUMBER bigint,
BALANCE int,
AADHAR bigint
);
INSERT INTO PAWAR VALUES(1234,50000,2);
INSERT INTO PAWAR VALUES(5898,40000,3);
INSERT INTO PAWAR VALUES(9872,30000,2);
INSERT INTO PAWAR VALUES(8796,90000,5);
SELECT * FROM PAWAR;


--INNER JOIN
SELECT SACHIN.FIRSTNAME,
SACHIN.LASTNAME,
PAWAR.BALANCE
FROM SACHIN INNER JOIN PAWAR
ON SACHIN.AADHAR = PAWAR.AADHAR;

--LEFT JOIN
SELECT SACHIN.FIRSTNAME,
SACHIN.LASTNAME,
PAWAR.BALANCE
FROM SACHIN LEFT JOIN PAWAR
ON SACHIN.AADHAR = PAWAR.AADHAR;

-- RIGHT JOIN
SELECT SACHIN.FIRSTNAME,
SACHIN.LASTNAME,
PAWAR.BALANCE
FROM SACHIN RIGHT JOIN PAWAR
ON SACHIN.AADHAR = PAWAR.AADHAR;

-- FULL JOIN
SELECT SACHIN.FIRSTNAME,
SACHIN.LASTNAME,
PAWAR.BALANCE
FROM SACHIN FULL JOIN PAWAR
ON SACHIN.AADHAR = PAWAR.AADHAR;


