CREATE DATABASE FOREIGNKEY;
CREATE TABLE UIDAI
(
AADHARNO bigint,
FIRSTNAME varchar(255) NOT NULL,
LASTNAME varchar(25),
MOBILENO bigint UNIQUE,
EMAILID varchar(25) UNIQUE,
PANCARD varchar(25) UNIQUE,
CITY varchar(25),
PRIMARY KEY (AADHARNO)
);
SELECT * FROM UIDAI;

CREATE TABLE ICICI(
FIRSTNAME varchar(255),
LASTNAME varchar(255),
BALANCE bigint,
ACCOUNTNO int,
AADHARNO bigint,
FOREIGN KEY(AADHARNO) REFERENCES UIDAI(AADHARNO)
);
SELECT * FROM ICICI;

CREATE TABLE IDBI(
AADHARNO bigint,
BALANCE int,
FOREIGN KEY (AADHARNO) REFERENCES UIDAI(AADHARNO)
);
SELECT * FROM IDBI;

CREATE TABLE Persons(
ID int NOT NULL,
FIRSTNAME varchar(255) NOT NULL,
LASTNAME varchar(255),
AGE int NOT NULL,
City varchar(255) DEFAULT 'Latur'
);
SELECT * FROM Persons;
INSERT INTO Persons VALUES(900,'MADHUMITA','KADAM',22,'');
SELECT * FROM Persons;
UPDATE Persons SET City ='Sangli' WHERE FIRSTNAME ='MADHUMITA';
SELECT * FROM Persons;
INSERT INTO Persons VALUES (850,'MAYA','POTE',32,DEFAULT);
SELECT * FROM Persons;

